on : push
jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '298.0.0'
      - run: gcloud info
      - name: gcloud
        run: |
         gcloud auth configure-docker
         git clone https://github.com/GoogleCloudPlatform/github-actions/
         cd github-actions/example-workflows/cloud-run/
         docker build .
